#!/usr/bin/env bash

echo "Post checkout hook fired"
echo "======================"

echo ""

echo "Running ctags"
./.git_hooks/parse.py .

echo ""
echo "Post checkout done"
echo "================"

echo ""
