#!/usr/bin/env bash

echo "Post commit hook fired"
echo "======================"

echo ""

echo "Running ctags"
./.git_hooks/parse.py .

echo ""
echo "Post commit done"
echo "================"

echo ""
