#build64:
#    variables:
#        GIT_SUBMODULE_STRATEGY: recursive
#    script:
#        - source /tools/setup.sh
#        - make restore 
#        - make patch
#        - make generate_verilog SYNTH=SIM MUL=fpga ISA=RV64IMAC MULSTAGES=8 DIVSTAGES=64
#        - make link_verilator generate_boot_files
#        - make regress opts='--filter=rv64 --parallel=90 --sub'
#        - make regress opts='--filter=rv64 --final'
#    only:
#        - master
#    tags:
#        - e-class-build-regression
#        
#build32:
#    variables:
#        GIT_SUBMODULE_STRATEGY: recursive
#    script:
#        - source /tools/setup.sh
#        - make restore 
#        - make patch
#        - make generate_verilog SYNTH=SIM MUL=fpga ISA=RV32IMAC MULSTAGES=4 DIVSTAGES=32
#        - make link_verilator generate_boot_files MUL=fpga ISA=RV32IMAC MULSTAGES=4 DIVSTAGES=32
#        - make regress opts='--filter=rv32 --sub --parallel=90' CONFIG_ISA=RV32IMAC
#        - make regress opts='--filter=rv32 --final'
#    only:
#        - master
#    tags:
#        - e-class-build-regression

gen_artifacts:
    variables:
        GIT_SUBMODULE_STRATEGY: recursive
    script:
        - source /tools/setup.sh
        - make restore 
        - make generate_verilog SYNTH=SIM MUL=fpga ISA=RV64IMAC MULSTAGES=8 DIVSTAGES=64 RTLDUMP=False
        - tar -cvzf verilog_eclassrv64imac.tar.gz verilog/
        - make restore 
        - make generate_verilog SYNTH=SIM MUL=fpga ISA=RV32IMAC MULSTAGES=4 DIVSTAGES=32 RTLDUMP=False
        - tar -cvzf verilog_eclassrv32imac.tar.gz verilog/
    artifacts:
        paths:
            - verilog_eclassrv64imac.tar.gz
            - verilog_eclassrv32imac.tar.gz
    only:
        - 35-generating_artifcats
    tags:
        - e-class-build-regression

