stages:
    - build64
    
build64:
    stage: build64
    script:
        - /home/rise/runner_setup.sh
        - make restore 
        - make compile_bluesim ISA=RV64IMAC MULSTAGES=8 DIVSTAGES=64
        - make link_bluesim generate_boot_files
        - make regress opts='--filter=rv64 --parallel=50 --sub'
        - make regress opts='--filter=rv64 --final'
    only:
        - master
